version: '3.8'

services:

  nginx:
    depends_on:
      - apollo-server
      - api-builder
#      - web-client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "4000:80"

  apollo-server:
    build:
      dockerfile: Dockerfile
      context: ./apollo-server
    volumes:
      - ./apollo-server:/app

  api-builder:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./api-builder
    volumes:
      - ./api-builder:/app

#  web-client:
#    stdin_open: true
#    ports:
#      - "8000:8000"
#    depends_on:
#      - apollo-server
#    build:
#      dockerfile: Dockerfile
#      context: ./web-client
#    volumes:
#      - ./web-client:/app
