version: '3.8'

services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "4000:80"

  api:
    build:
      dockerfile: Dockerfile
      context: ./server-api
    volumes:
      - ./server-api:/app

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./web-client
    volumes:
      - ./web-client:/app

